{
	"name": "Asset Management System",
	"version": "1.0", 
	"depends": [
		"account",
		"om_account_accountant",
		"om_account_asset",
		"purchase",
		"stock",
	],
	"author": "vITraining [ Akhmad D. Sembiring, Miftahussalam ]",
	"category": "Accounting",
	'website': 'https://vitraining.com/',
	'images': ['static/description/images/main_screenshot.jpg'],
	'price': '500',
	'currency': 'USD',
	'summary': 'Full Asset Management System',
	"description": "",
	"data": [
		"security/groups.xml",
		"security/ir_rule.xml",
		"top_menu.xml",
		"data/ir_sequence.xml",
		"data/res.partner.category.csv",
		"views/asset.xml",
		"views/asset_detail.xml",
		"views/category.xml",
		"views/disposal.xml",
		"views/transfer.xml",
		"views/location.xml",
		"views/maintenance.xml",
		"views/reclass.xml",
		"views/reval.xml",
		"views/physical.xml",
		"views/report.xml",
		"wizard/account_depreciation_confirmation_wizard_views.xml",
		"report/asset_label.xml",
		"security/ir.model.access.csv",
	],
	"installable": True,
	"auto_install": False,
    "application": True,
}